### ISSUE TITLE
"flip" type needs incorrect formatting in rules.yml

### ISSUE THREAD

**Issue by cafestifflered** [cafestifflered/ChatRestrict#11]
When using the "flip" type for a rule, the standard rule structure for tabbing in rules.yml cannot be followed.

This works (notice no tab on the "flip" rule - the flipped rule also does not show in tab-autocomplete of `/chatrestrict <enable/disable> [rulename]`):
```
rules:
  chat-allowed:
    type: "ruleset"
    rules:
      chat-days:
        type: "allowed_weekdays"
        week_days: ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"]
      chat-time:
        type: "allowed_timerange"
        time_min: "3:00 AM"
        time_max: "11:59 PM"
        zone: "EST"
  command-blocklist:
    type: "disallowed_commands"
    commands: "comma, separated, list_of_commands"
chat-blocked:
  type: "flip"
  rules:
    type: "allowed_weekdays"
    week_days: ["MONDAY"]
```

This does not work (with proper tabbing - throws an error):
```
rules:
  chat-allowed:
    type: "ruleset"
    rules:
      chat-days:
        type: "allowed_weekdays"
        week_days: ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"]
      chat-time:
        type: "allowed_timerange"
        time_min: "3:00 AM"
        time_max: "11:59 PM"
        zone: "EST"
  command-blocklist:
    type: "disallowed_commands"
    commands: "comma, separated, list_of_commands"
  chat-blocked:
    type: "flip"
    rules:
      type: "allowed_weekdays"
      week_days: ["MONDAY"]
```

This also _technically_ works, but then the `/chatrestrict <enable/disable>` command does not show the rules in tab autocomplete. The difference here is there is no prepended `rules:` line at the start.
```
chat-allowed:
  type: "ruleset"
  rules:
    chat-days:
      type: "allowed_weekdays"
      week_days: ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"]
    chat-time:
      type: "allowed_timerange"
      time_min: "3:00 AM"
      time_max: "11:59 PM"
      zone: "EST"
command-blocklist:
  type: "disallowed_commands"
  commands: "comma, separated, list_of_commands"
chat-blocked:
  type: "flip"
  rules:
    type: "allowed_weekdays"
    week_days: ["MONDAY"]
```

**Comment by Owen1212055** [comment]
The issue is the syntax that flip expects is documented incorrectly. I have fixed this, and changed it to ``rule``. An example here.
```yml
rules:
  my-cool-rule:
    type: "flip"
    rule:
      type: "allowed_weekdays"
      week_days: ["MONDAY", "TUESDAY"]
```

**Comment by cafestifflered** [comment]
Following the corrected format, error in console and no rules registered.
```
rules:
  chat-allowed:
    type: "ruleset"
    rules:
      chat-days:
        type: "allowed_weekdays"
        week_days: ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"]
      chat-time:
        type: "allowed_timerange"
        time_min: "3:00 AM"
        time_max: "11:59 PM"
        zone: "EST"
  command-blocklist:
    type: "disallowed_commands"
    commands: ["cr_comma", "cr_separated", "cr_list_of_commands"]
  flipped-rule:
    type: "flip"
      rule:
        type: "allowed_timerange"
        time_min: "4:32 AM"
        time_max: "4:33 AM"
        zone: "EST"
```
```
[11:45:52 INFO]: stifflered issued server command: /chatrestrict reload
[11:45:52 ERROR]: Cannot load plugins/ChatRestrict/rules.yml
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'reader', line 17, column 5:
        type: "flip"
        ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 18, column 7:
          rule:
          ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:304) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at com.stifflered.chatrestrict.ChatRestrictPlugin.saveDefaultResourceOrGet(ChatRestrictPlugin.java:81) ~[ChatRestrict-all.jar:?]
	at com.stifflered.chatrestrict.ChatRestrictPlugin.getRules(ChatRestrictPlugin.java:64) ~[ChatRestrict-all.jar:?]
	at com.stifflered.chatrestrict.predicate.PredicateHandler.<init>(PredicateHandler.java:28) ~[ChatRestrict-all.jar:?]
	at com.stifflered.chatrestrict.ChatRestrictPlugin.reloadConfigs(ChatRestrictPlugin.java:59) ~[ChatRestrict-all.jar:?]
	at com.stifflered.chatrestrict.commands.ChatRestrictCommand.execute(ChatRestrictCommand.java:42) ~[ChatRestrict-all.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2307) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2118) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2099) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1348) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-379]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 17, column 5:
        type: "flip"
        ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 18, column 7:
          rule:
          ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:644) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:166) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:214) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:184) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:142) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.Yaml.compose(Yaml.java:575) ~[snakeyaml-1.30.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:102) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	... 29 more
[11:45:52 INFO]: [ChatRestrict] Registered 0 predicates
```
